version: "3.3"
services:
# app name
  nest-app:
  # container name when running and building
    container_name: nestjs-app-containerized
    # the image to use
    image: nestjs-app
    # ports to expose
    ports:
      - "3000:3000"
    env_file:
      - ./.env
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

