version: "3.3"
services:
  nest-app:
    build:
      context: .
      target: production
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
      - PORT=3000
    command:
      - npm start:dev
